// warning: This file is auto generated by `yarn build:tests`
// Do not edit by hand!

'use strict'

process.env.TZ = 'UTC'
var expect = require('chai').expect
var ini_set = require('../../../../src/php/info/ini_set') // eslint-disable-line no-unused-vars,camelcase
var ini_get = require('../../../../src/php/info/ini_get') // eslint-disable-line no-unused-vars,camelcase
var getdate = require('../../../../src/php/datetime/getdate.js') // eslint-disable-line no-unused-vars,camelcase

describe('src/php/datetime/getdate.js (tested in test/languages/php/datetime/test-getdate.js)', function () {
  it('should pass example 1', function (done) {
    var expected = {'seconds': 40, 'minutes': 58, 'hours': 1, 'mday': 18, 'wday': 3, 'mon': 6, 'year': 2003, 'yday': 168, 'weekday': 'Wednesday', 'month': 'June', '0': 1055901520}
    var result = getdate(1055901520)
    expect(result).to.deep.equal(expected)
    done()
  })
})
