atom ./src/golang/strings/Count.js \
./src/golang/strings/Count.js \
./src/php/array/array_flip.js \
./src/php/array/array_merge_recursive.js \
./src/php/array/array_search.js \
./src/php/array/array_slice.js \
./src/php/array/array_splice.js \
./src/php/array/array_walk.js \
./src/php/array/arsort.js \
./src/php/array/asort.js \
./src/php/array/asort.js \
./src/php/array/krsort.js \
./src/php/array/krsort.js \
./src/php/array/ksort.js \
./src/php/array/ksort.js \
./src/php/array/natcasesort.js \
./src/php/array/natsort.js \
./src/php/array/pos.js \
./src/php/array/rsort.js \
./src/php/array/sizeof.js \
./src/php/array/sort.js \
./src/php/bc/bcadd.js \
./src/php/bc/bccomp.js \
./src/php/bc/bcdiv.js \
./src/php/bc/bcmul.js \
./src/php/bc/bcround.js \
./src/php/bc/bcscale.js \
./src/php/bc/bcsub.js \
./src/php/ctype/ctype_alnum.js \
./src/php/ctype/ctype_alpha.js \
./src/php/ctype/ctype_cntrl.js \
./src/php/ctype/ctype_digit.js \
./src/php/ctype/ctype_graph.js \
./src/php/ctype/ctype_lower.js \
./src/php/ctype/ctype_print.js \
./src/php/ctype/ctype_punct.js \
./src/php/ctype/ctype_space.js \
./src/php/ctype/ctype_upper.js \
./src/php/ctype/ctype_xdigit.js \
./src/php/datetime/date_parse.js \
./src/php/datetime/gmdate.js \
./src/php/datetime/gmstrftime.js \
./src/php/datetime/strftime.js \
./src/php/datetime/strftime.js \
./src/php/datetime/strptime.js \
./src/php/datetime/strptime.js \
./src/php/filesystem/pathinfo.js \
./src/php/i18n/i18n_loc_get_default.js \
./src/php/network/setcookie.js \
./src/php/pcre/sql_regcase.js \
./src/php/pcre/sql_regcase.js \
./src/php/strings/chop.js \
./src/php/strings/convert_uuencode.js \
./src/php/strings/crc32.js \
./src/php/strings/html_entity_decode.js \
./src/php/strings/htmlentities.js \
./src/php/strings/join.js \
./src/php/strings/localeconv.js \
./src/php/strings/md5.js \
./src/php/strings/md5_file.js \
./src/php/strings/md5_file.js \
./src/php/strings/money_format.js \
./src/php/strings/nl_langinfo.js \
./src/php/strings/printf.js \
./src/php/strings/setlocale.js \
./src/php/strings/setlocale.js \
./src/php/strings/sha1_file.js \
./src/php/strings/sha1_file.js \
./src/php/strings/split.js \
./src/php/strings/str_word_count.js \
./src/php/strings/strchr.js \
./src/php/strings/strcoll.js \
./src/php/strings/strnatcmp.js \
./src/php/strings/strtr.js \
./src/php/strings/strtr.js \
./src/php/strings/vprintf.js \
./src/php/strings/vsprintf.js \
./src/php/url/get_headers.js \
./src/php/url/get_meta_tags.js \
./src/php/url/http_build_query.js \
./src/php/var/doubleval.js \
./src/php/var/gettype.js \
./src/php/var/is_double.js \
./src/php/var/is_integer.js \
./src/php/var/is_long.js \
./src/php/var/is_real.js \
./src/php/var/print_r.js \
./src/php/var/strval.js \
./src/php/var/var_dump.js \
./src/php/var/var_export.js \
|| false
