// warning: This file is auto generated by `npm run build:tests`, do not edit by hand
var XMLHttpRequest = {} // eslint-disable-line no-native-reassign
var window = { // eslint-disable-line no-native-reassign
  window: {},
  document: {
    lastModified: 1388954399,
    getElementsByTagName: function () { return [] }
  },
  location: {
    href: ""
  }
}
process.env.TZ = 'UTC'
var expect = require('chai').expect
var ini_set = require('/Users/kvz/code/phpjs/src/php/info/ini_set') // eslint-disable-line no-unused-vars
var ini_get = require('/Users/kvz/code/phpjs/src/php/info/ini_get') // eslint-disable-line no-unused-vars
var long2ip = require('/Users/kvz/code/phpjs/src/php/network/long2ip.js')

describe('src/php/network/long2ip.js', function () {
  it('should pass example 1', function (done) {
    long2ip( 3221234342 )
    var expected = '192.0.34.166'
    var result = long2ip( 3221234342 )
    expect(result).to.deep.equal(expected)
    done()
  })
})