module.exports.lc = require('./lc')
module.exports.length = require('./length')
module.exports.reverse = require('./reverse')
module.exports.substr = require('./substr')
module.exports.uc = require('./uc')
