// warning: This file is auto generated by `npm run build:tests`, do not edit by hand
process.env.TZ = 'UTC'
var expect = require('chai').expect
var ini_set = require('/Users/kvz/code/phpjs/src/php/info/ini_set') // eslint-disable-line no-unused-vars
var ini_get = require('/Users/kvz/code/phpjs/src/php/info/ini_get') // eslint-disable-line no-unused-vars
var getenv = require('/Users/kvz/code/phpjs/src/php/info/getenv.js')

describe('src/php/info/getenv.js', function () {
  it('should pass example 1', function (done) {
    getenv('LC_ALL')
    var expected = false
    var result = getenv('LC_ALL')
    expect(result).to.deep.equal(expected)
    done()
  })
})