// warning: This file is auto generated by `npm run build:tests`, do not edit by hand
process.env.TZ = 'UTC'
var expect = require('chai').expect
var ini_set = require('/Users/kvz/code/phpjs/src/php/info/ini_set') // eslint-disable-line no-unused-vars
var ini_get = require('/Users/kvz/code/phpjs/src/php/info/ini_get') // eslint-disable-line no-unused-vars
var ini_get = require('/Users/kvz/code/phpjs/src/php/info/ini_get.js')

describe('src/php/info/ini_get.js', function () {
  it('should pass example 1', function (done) {
    ini_set('date.timezone', 'Asia/Hong_Kong')
    ini_get('date.timezone')
    var expected = 'Asia/Hong_Kong'
ini_set('date.timezone', 'Asia/Hong_Kong')
    var result = ini_get('date.timezone')
    expect(result).to.deep.equal(expected)
    done()
  })
})