export { getArrayLikeLength, getEntryAtCursor, getPointerState } from './_arrayPointers.ts'
export { _bc } from './_bc.ts'
export { resolveNumericComparator, resolvePhpCallable } from './_callbackResolver.ts'
export { _php_cast_float } from './_php_cast_float.ts'
export { _php_cast_int } from './_php_cast_int.ts'
export { _phpCastString } from './_phpCastString.ts'
export { ensurePhpRuntimeState, setPhpLocaleDefault } from './_phpRuntimeState.ts'
export { isObjectLike, isPhpArrayObject, toPhpArrayObject } from './_phpTypes.ts'
