// warning: This file is auto generated by `npm run build:tests`, do not edit by hand
var XMLHttpRequest = {} // eslint-disable-line no-native-reassign
var window = { // eslint-disable-line no-native-reassign
  window: {},
  document: {
    lastModified: 1388954399,
    getElementsByTagName: function () { return [] }
  },
  location: {
    href: ""
  }
}
process.env.TZ = 'UTC'
var expect = require('chai').expect
var ini_set = require('/Users/kvz/code/phpjs/src/php/info/ini_set') // eslint-disable-line no-unused-vars
var ini_get = require('/Users/kvz/code/phpjs/src/php/info/ini_get') // eslint-disable-line no-unused-vars
var is_null = require('/Users/kvz/code/phpjs/src/php/var/is_null.js')

describe('src/php/var/is_null.js', function () {
  it('should pass example 1', function (done) {
    is_null('23')
    var expected = false
    var result = is_null('23')
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 2', function (done) {
    is_null(null)
    var expected = true
    var result = is_null(null)
    expect(result).to.deep.equal(expected)
    done()
  })
})