// warning: This file is auto generated by `npm run build:tests`, do not edit by hand
process.env.TZ = 'UTC'
var expect = require('chai').expect
var ini_set = require('../../../../src/php/info/ini_set') // eslint-disable-line no-unused-vars,camelcase
var ini_get = require('../../../../src/php/info/ini_get') // eslint-disable-line no-unused-vars,camelcase
var intval = require('../../../../src/php/var/intval.js') // eslint-disable-line no-unused-vars,camelcase

describe('src/php/var/intval.js (tested in test/languages/php/var/test-intval.js)', function () {
  it('should pass example 1', function (done) {
    var expected = 0
    var result = intval('Kevin van Zonneveld')
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 2', function (done) {
    var expected = 4
    var result = intval(4.2)
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 3', function (done) {
    var expected = 42
    var result = intval(42, 8)
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 4', function (done) {
    var expected = 9
    var result = intval('09')
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 5', function (done) {
    var expected = 30
    var result = intval('1e', 16)
    expect(result).to.deep.equal(expected)
    done()
  })
})
