// warning: This file is auto generated by `yarn build:tests`
// Do not edit by hand!

'use strict'

process.env.TZ = 'UTC'
var expect = require('chai').expect
var ini_set = require('../../../../src/php/info/ini_set') // eslint-disable-line no-unused-vars,camelcase
var ini_get = require('../../../../src/php/info/ini_get') // eslint-disable-line no-unused-vars,camelcase
var boolval = require('../../../../src/php/var/boolval.js') // eslint-disable-line no-unused-vars,camelcase

describe('src/php/var/boolval.js (tested in test/languages/php/var/test-boolval.js)', function () {
  it('should pass example 1', function (done) {
    var expected = true
    var result = boolval(true)
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 2', function (done) {
    var expected = false
    var result = boolval(false)
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 3', function (done) {
    var expected = false
    var result = boolval(0)
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 4', function (done) {
    var expected = false
    var result = boolval(0.0)
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 5', function (done) {
    var expected = false
    var result = boolval('')
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 6', function (done) {
    var expected = false
    var result = boolval('0')
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 7', function (done) {
    var expected = false
    var result = boolval([])
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 8', function (done) {
    var expected = false
    var result = boolval('')
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 9', function (done) {
    var expected = false
    var result = boolval(null)
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 10', function (done) {
    var expected = false
    var result = boolval(undefined)
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 11', function (done) {
    var expected = true
    var result = boolval('true')
    expect(result).to.deep.equal(expected)
    done()
  })
})
