// warning: This file is auto generated by `npm run build:tests`, do not edit by hand
process.env.TZ = 'UTC'
var expect = require('chai').expect
var ini_set = require('/Users/kvz/code/phpjs/src/php/info/ini_set') // eslint-disable-line no-unused-vars
var ini_get = require('/Users/kvz/code/phpjs/src/php/info/ini_get') // eslint-disable-line no-unused-vars
var strval = require('/Users/kvz/code/phpjs/src/php/var/strval.js')

describe('src/php/var/strval.js', function () {
  it('should pass example 1', function (done) {
    strval({red: 1, green: 2, blue: 3, white: 4})
    var expected = 'Object'
    var result = strval({red: 1, green: 2, blue: 3, white: 4})
    expect(result).to.deep.equal(expected)
    done()
  })
})