// warning: This file is auto generated by `npm run build:tests`, do not edit by hand
process.env.TZ = 'UTC'
var expect = require('chai').expect
var ini_set = require('../../../../src/php/info/ini_set') // eslint-disable-line no-unused-vars,camelcase
var ini_get = require('../../../../src/php/info/ini_get') // eslint-disable-line no-unused-vars,camelcase
var bcdiv = require('../../../../src/php/bc/bcdiv.js') // eslint-disable-line no-unused-vars,camelcase

describe('src/php/bc/bcdiv.js', function () {
  it('should pass example 1', function (done) {
    bcdiv(1, 2)
    var expected = '0'
    var result = bcdiv(1, 2)
    expect(result).to.deep.equal(expected)
    done()
  })
})