// warning: This file is auto generated by `npm run build:tests`, do not edit by hand
process.env.TZ = 'UTC'
var expect = require('chai').expect
var ini_set = require('../../../../src/php/info/ini_set') // eslint-disable-line no-unused-vars,camelcase
var ini_get = require('../../../../src/php/info/ini_get') // eslint-disable-line no-unused-vars,camelcase
var bcadd = require('../../../../src/php/bc/bcadd.js') // eslint-disable-line no-unused-vars,camelcase

describe('src/php/bc/bcadd.js', function () {
  it('should pass example 1', function (done) {
    bcadd(1, 2)
    var expected = '3'
    var result = bcadd(1, 2)
    expect(result).to.deep.equal(expected)
    done()
  })
})