// warning: This file is auto generated by `npm run build:tests`
// Do not edit by hand!
process.env.TZ = 'UTC'
var ini_set = require('../../../../src/php/info/ini_set') // eslint-disable-line no-unused-vars,camelcase
var ini_get = require('../../../../src/php/info/ini_get') // eslint-disable-line no-unused-vars,camelcase
var bcsub = require('../../../../src/php/bc/bcsub.js') // eslint-disable-line no-unused-vars,camelcase

describe('src/php/bc/bcsub.js (tested in test/languages/php/bc/test-bcsub.js)', function () {
  it('should pass example 1', function (done) {
    var expected = '-1'
    var result = bcsub('1', '2')
    expect(result).toEqual(expected)
    done()
  })
  it('should pass example 2', function (done) {
    var expected = '-6.0000'
    var result = bcsub('-1', '5', 4)
    expect(result).toEqual(expected)
    done()
  })
  it('should pass example 3', function (done) {
    var expected = '8728932000054820705086578390258.00'
    var result = bcsub('8728932001983192837219398127471', '1928372132132819737213', 2)
    expect(result).toEqual(expected)
    done()
  })
})
