// warning: This file is auto generated by `yarn build:tests`
// Do not edit by hand!
process.env.TZ = 'UTC'
var expect = require('chai').expect
var ini_set = require('../../../../src/php/info/ini_set') // eslint-disable-line no-unused-vars,camelcase
var ini_get = require('../../../../src/php/info/ini_get') // eslint-disable-line no-unused-vars,camelcase
var dirname = require('../../../../src/php/filesystem/dirname.js') // eslint-disable-line no-unused-vars,camelcase

describe('src/php/filesystem/dirname.js (tested in test/languages/php/filesystem/test-dirname.js)', function () {
  it('should pass example 1', function (done) {
    var expected = '/etc'
    var result = dirname('/etc/passwd')
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 2', function (done) {
    var expected = 'c:/Temp'
    var result = dirname('c:/Temp/x')
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 3', function (done) {
    var expected = '/dir'
    var result = dirname('/dir/test/')
    expect(result).to.deep.equal(expected)
    done()
  })
})
