// warning: This file is auto generated by `npm run build:tests`, do not edit by hand
process.env.TZ = 'UTC'
var expect = require('chai').expect
var ini_set = require('../../../../src/php/info/ini_set') // eslint-disable-line no-unused-vars,camelcase
var ini_get = require('../../../../src/php/info/ini_get') // eslint-disable-line no-unused-vars,camelcase
var log = require('../../../../src/php/math/log.js') // eslint-disable-line no-unused-vars,camelcase

describe('src/php/math/log.js (tested in test/languages/php/math/test-log.js)', function () {
  it('should pass example 1', function (done) {
    var expected = 8.212871815082147
    var result = log(8723321.4, 7)
    expect(result).to.deep.equal(expected)
    done()
  })
})