// warning: This file is auto generated by `yarn build:tests`
// Do not edit by hand!

'use strict'

process.env.TZ = 'UTC'
var expect = require('chai').expect
var ini_set = require('../../../../src/php/info/ini_set') // eslint-disable-line no-unused-vars,camelcase
var ini_get = require('../../../../src/php/info/ini_get') // eslint-disable-line no-unused-vars,camelcase
var tanh = require('../../../../src/php/math/tanh.js') // eslint-disable-line no-unused-vars,camelcase

describe('src/php/math/tanh.js (tested in test/languages/php/math/test-tanh.js)', function () {
  it('should pass example 1', function (done) {
    var expected = 0.9999612058841574
    var result = tanh(5.4251848798444815)
    expect(result).to.deep.equal(expected)
    done()
  })
})
