// warning: This file is auto generated by `npm run build:tests`, do not edit by hand
process.env.TZ = 'UTC'
var expect = require('chai').expect
var ini_set = require('/Users/kvz/code/phpjs/src/php/info/ini_set') // eslint-disable-line no-unused-vars
var ini_get = require('/Users/kvz/code/phpjs/src/php/info/ini_get') // eslint-disable-line no-unused-vars
var sin = require('/Users/kvz/code/phpjs/src/php/math/sin.js')

describe('src/php/math/sin.js', function () {
  it('should pass example 1', function (done) {
    Math.ceil(sin(8723321.4) * 10000000)
    var expected = -9834330
    var result = Math.ceil(sin(8723321.4) * 10000000)
    expect(result).to.deep.equal(expected)
    done()
  })
})