// warning: This file is auto generated by `npm run build:tests`, do not edit by hand
process.env.TZ = 'UTC'
var expect = require('chai').expect
var ini_set = require('/Users/kvz/code/phpjs/src/php/info/ini_set') // eslint-disable-line no-unused-vars
var ini_get = require('/Users/kvz/code/phpjs/src/php/info/ini_get') // eslint-disable-line no-unused-vars
var hypot = require('/Users/kvz/code/phpjs/src/php/math/hypot.js')

describe('src/php/math/hypot.js', function () {
  it('should pass example 1', function (done) {
    hypot(3, 4)
    var expected = 5
    var result = hypot(3, 4)
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 2', function (done) {
    hypot([], 'a')
    var expected = null
    var result = hypot([], 'a')
    expect(result).to.deep.equal(expected)
    done()
  })
})