// warning: This file is auto generated by `npm run build:tests`, do not edit by hand
process.env.TZ = 'UTC'
var expect = require('chai').expect
var ini_set = require('../../../../src/php/info/ini_set') // eslint-disable-line no-unused-vars,camelcase
var ini_get = require('../../../../src/php/info/ini_get') // eslint-disable-line no-unused-vars,camelcase
var max = require('../../../../src/php/math/max.js') // eslint-disable-line no-unused-vars,camelcase

describe('src/php/math/max.js (tested in test/languages/php/math/test-max.js)', function () {
  it('should pass example 1', function (done) {
    var expected = 7
    var result = max(1, 3, 5, 6, 7)
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 2', function (done) {
    var expected = 5
    var result = max([2, 4, 5])
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 3', function (done) {
    var expected = 0
    var result = max(0, 'hello')
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 4', function (done) {
    var expected = 'hello'
    var result = max('hello', 0)
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 5', function (done) {
    var expected = 'hello'
    var result = max(-1, 'hello')
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 6', function (done) {
    var expected = [2, 5, 7]
    var result = max([2, 4, 8], [2, 5, 7])
    expect(result).to.deep.equal(expected)
    done()
  })
})
