// warning: This file is auto generated by `npm run build:tests`, do not edit by hand
process.env.TZ = 'UTC'
var expect = require('chai').expect
var ini_set = require('/Users/kvz/code/phpjs/src/php/info/ini_set') // eslint-disable-line no-unused-vars
var ini_get = require('/Users/kvz/code/phpjs/src/php/info/ini_get') // eslint-disable-line no-unused-vars
var expm1 = require('/Users/kvz/code/phpjs/src/php/math/expm1.js')

describe('src/php/math/expm1.js', function () {
  it('should pass example 1', function (done) {
    expm1(1e-15)
    var expected = 1.0000000000000007e-15
    var result = expm1(1e-15)
    expect(result).to.deep.equal(expected)
    done()
  })
})