// warning: This file is auto generated by `npm run build:tests`
// Do not edit by hand!
process.env.TZ = 'UTC'
var ini_set = require('../../../../src/php/info/ini_set') // eslint-disable-line no-unused-vars,camelcase
var ini_get = require('../../../../src/php/info/ini_get') // eslint-disable-line no-unused-vars,camelcase
var min = require('../../../../src/php/math/min.js') // eslint-disable-line no-unused-vars,camelcase

describe('src/php/math/min.js (tested in test/languages/php/math/test-min.js)', function () {
  it('should pass example 1', function (done) {
    var expected = 1
    var result = min(1, 3, 5, 6, 7)
    expect(result).toEqual(expected)
    done()
  })
  it('should pass example 2', function (done) {
    var expected = 2
    var result = min([2, 4, 5])
    expect(result).toEqual(expected)
    done()
  })
  it('should pass example 3', function (done) {
    var expected = 0
    var result = min(0, 'hello')
    expect(result).toEqual(expected)
    done()
  })
  it('should pass example 4', function (done) {
    var expected = 'hello'
    var result = min('hello', 0)
    expect(result).toEqual(expected)
    done()
  })
  it('should pass example 5', function (done) {
    var expected = -1
    var result = min(-1, 'hello')
    expect(result).toEqual(expected)
    done()
  })
  it('should pass example 6', function (done) {
    var expected = [2, 4, 8]
    var result = min([2, 4, 8], [2, 5, 7])
    expect(result).toEqual(expected)
    done()
  })
})
