// warning: This file is auto generated by `npm run build:tests`, do not edit by hand
process.env.TZ = 'UTC'
var expect = require('chai').expect
var ini_set = require('/Users/kvz/code/phpjs/src/php/info/ini_set') // eslint-disable-line no-unused-vars
var ini_get = require('/Users/kvz/code/phpjs/src/php/info/ini_get') // eslint-disable-line no-unused-vars
var octdec = require('/Users/kvz/code/phpjs/src/php/math/octdec.js')

describe('src/php/math/octdec.js', function () {
  it('should pass example 1', function (done) {
    octdec('77')
    var expected = 63
    var result = octdec('77')
    expect(result).to.deep.equal(expected)
    done()
  })
})