// warning: This file is auto generated by `npm run build:tests`, do not edit by hand
process.env.TZ = 'UTC'
var expect = require('chai').expect
var ini_set = require('../../../../src/php/info/ini_set') // eslint-disable-line no-unused-vars,camelcase
var ini_get = require('../../../../src/php/info/ini_get') // eslint-disable-line no-unused-vars,camelcase
var chr = require('../../../../src/php/strings/chr.js') // eslint-disable-line no-unused-vars,camelcase

describe('src/php/strings/chr.js', function () {
  it('should pass example 1', function (done) {
    chr(75) === 'K'
    chr(65536) === '\uD800\uDC00'
    var expected = true
    true
    chr(75) === 'K'
    var result = chr(65536) === '\uD800\uDC00'
    expect(result).to.deep.equal(expected)
    done()
  })
})