// warning: This file is auto generated by `npm run build:tests`, do not edit by hand
process.env.TZ = 'UTC'
var expect = require('chai').expect
var ini_set = require('../../../../src/php/info/ini_set') // eslint-disable-line no-unused-vars,camelcase
var ini_get = require('../../../../src/php/info/ini_get') // eslint-disable-line no-unused-vars,camelcase
var strncmp = require('../../../../src/php/strings/strncmp.js') // eslint-disable-line no-unused-vars,camelcase

describe('src/php/strings/strncmp.js', function () {
  it('should pass example 1', function (done) {
    strncmp('aaa', 'aab', 2)
    var expected = 0
    var result = strncmp('aaa', 'aab', 2)
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 2', function (done) {
    strncmp('aaa', 'aab', 3 )
    var expected = -1
    var result = strncmp('aaa', 'aab', 3 )
    expect(result).to.deep.equal(expected)
    done()
  })
})