// warning: This file is auto generated by `npm run build:tests`, do not edit by hand
process.env.TZ = 'UTC'
var expect = require('chai').expect
var ini_set = require('../../../../src/php/info/ini_set') // eslint-disable-line no-unused-vars,camelcase
var ini_get = require('../../../../src/php/info/ini_get') // eslint-disable-line no-unused-vars,camelcase
var stristr = require('../../../../src/php/strings/stristr.js') // eslint-disable-line no-unused-vars,camelcase

describe('src/php/strings/stristr.js (tested in test/languages/php/strings/test-stristr.js)', function () {
  it('should pass example 1', function (done) {
    var expected = 'van Zonneveld'
    var result = stristr('Kevin van Zonneveld', 'Van')
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 2', function (done) {
    var expected = 'Kevin '
    var result = stristr('Kevin van Zonneveld', 'VAN', true)
    expect(result).to.deep.equal(expected)
    done()
  })
})
