// warning: This file is auto generated by `npm run build:tests`, do not edit by hand
process.env.TZ = 'UTC'
var expect = require('chai').expect
var ini_set = require('/Users/kvz/code/phpjs/src/php/info/ini_set') // eslint-disable-line no-unused-vars
var ini_get = require('/Users/kvz/code/phpjs/src/php/info/ini_get') // eslint-disable-line no-unused-vars
var ucwords = require('/Users/kvz/code/phpjs/src/php/strings/ucwords.js')

describe('src/php/strings/ucwords.js', function () {
  it('should pass example 1', function (done) {
    ucwords('kevin van  zonneveld')
    var expected = 'Kevin Van  Zonneveld'
    var result = ucwords('kevin van  zonneveld')
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 2', function (done) {
    ucwords('HELLO WORLD')
    var expected = 'HELLO WORLD'
    var result = ucwords('HELLO WORLD')
    expect(result).to.deep.equal(expected)
    done()
  })
})