// warning: This file is auto generated by `yarn build:tests`
// Do not edit by hand!

'use strict'

process.env.TZ = 'UTC'
var expect = require('chai').expect
var ini_set = require('../../../../src/php/info/ini_set') // eslint-disable-line no-unused-vars,camelcase
var ini_get = require('../../../../src/php/info/ini_get') // eslint-disable-line no-unused-vars,camelcase
var sscanf = require('../../../../src/php/strings/sscanf.js') // eslint-disable-line no-unused-vars,camelcase

describe('src/php/strings/sscanf.js (tested in test/languages/php/strings/test-sscanf.js)', function () {
  it('should pass example 1', function (done) {
    var expected = [2350001]
    var result = sscanf('SN/2350001', 'SN/%d')
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 2', function (done) {
    var expected = 2350001
    var myVar = {}
    sscanf('SN/2350001', 'SN/%d', myVar)
    var result = myVar.value
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 3', function (done) {
    var expected = [20, 10]
    var result = sscanf("10--20", "%2$d--%1$d") // Must escape '$' in PHP, but not JS
    expect(result).to.deep.equal(expected)
    done()
  })
})
