// warning: This file is auto generated by `yarn build:tests`
// Do not edit by hand!

'use strict'

process.env.TZ = 'UTC'
var expect = require('chai').expect
var ini_set = require('../../../../src/php/info/ini_set') // eslint-disable-line no-unused-vars,camelcase
var ini_get = require('../../../../src/php/info/ini_get') // eslint-disable-line no-unused-vars,camelcase
var sprintf = require('../../../../src/php/strings/sprintf.js') // eslint-disable-line no-unused-vars,camelcase

describe('src/php/strings/sprintf.js (tested in test/languages/php/strings/test-sprintf.js)', function () {
  it('should pass example 1', function (done) {
    var expected = '123.10'
    var result = sprintf("%01.2f", 123.1)
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 2', function (done) {
    var expected = '[    monkey]'
    var result = sprintf("[%10s]", 'monkey')
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 3', function (done) {
    var expected = '[####monkey]'
    var result = sprintf("[%'#10s]", 'monkey')
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 4', function (done) {
    var expected = '123456789012345'
    var result = sprintf("%d", 123456789012345)
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 5', function (done) {
    var expected = 'E00'
    var result = sprintf('%-03s', 'E')
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 6', function (done) {
    var expected = '+000000009'
    var result = sprintf('%+010d', 9)
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 7', function (done) {
    var expected = '@@@@@@@@+9'
    var result = sprintf('%+0\'@10d', 9)
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 8', function (done) {
    var expected = '3.140000'
    var result = sprintf('%.f', 3.14)
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 9', function (done) {
    var expected = '% 2'
    var result = sprintf('%% %2$d', 1, 2)
    expect(result).to.deep.equal(expected)
    done()
  })
})
