// warning: This file is auto generated by `npm run build:tests`, do not edit by hand
XMLHttpRequest = {} // eslint-disable-line no-native-reassign
window = {
  window: {},
  document: {
    lastModified: 1388954399,
    getElementsByTagName: function () { return [] }
  },
  location: {
    href: ""
  }
} // eslint-disable-line no-native-reassign
process.env.TZ = 'UTC'
var expect = require('chai').expect
var ini_set = require('/Users/kvz/code/phpjs/src/php/info/ini_set')
var ini_get = require('/Users/kvz/code/phpjs/src/php/info/ini_get')
var strrchr = require('/Users/kvz/code/phpjs/src/php/strings/strrchr.js')

describe('php.strings.strrchr.js', function () {
  it('should pass example 1', function (done) {
    strrchr("Line 1\nLine 2\nLine 3", 10).substr(1)
    var expected = 'Line 3'
    var result = strrchr("Line 1\nLine 2\nLine 3", 10).substr(1)
    expect(result).to.deep.equal(expected)
    done()
  })
})