// warning: This file is auto generated by `npm run build:tests`, do not edit by hand
var XMLHttpRequest = {} // eslint-disable-line no-native-reassign
var window = { // eslint-disable-line no-native-reassign
  window: {},
  document: {
    lastModified: 1388954399,
    getElementsByTagName: function () { return [] }
  },
  location: {
    href: ""
  }
}
process.env.TZ = 'UTC'
var expect = require('chai').expect
var ini_set = require('/Users/kvz/code/phpjs/src/php/info/ini_set') // eslint-disable-line no-unused-vars
var ini_get = require('/Users/kvz/code/phpjs/src/php/info/ini_get') // eslint-disable-line no-unused-vars
var lcfirst = require('/Users/kvz/code/phpjs/src/php/strings/lcfirst.js')

describe('src/php/strings/lcfirst.js', function () {
  it('should pass example 1', function (done) {
    lcfirst('Kevin Van Zonneveld')
    var expected = 'kevin Van Zonneveld'
    var result = lcfirst('Kevin Van Zonneveld')
    expect(result).to.deep.equal(expected)
    done()
  })
})