// warning: This file is auto generated by `npm run build:tests`, do not edit by hand
process.env.TZ = 'UTC'
var expect = require('chai').expect
var ini_set = require('../../../../src/php/info/ini_set') // eslint-disable-line no-unused-vars,camelcase
var ini_get = require('../../../../src/php/info/ini_get') // eslint-disable-line no-unused-vars,camelcase
var strtr = require('../../../../src/php/strings/strtr.js') // eslint-disable-line no-unused-vars,camelcase

describe('src/php/strings/strtr.js (tested in test/languages/php/strings/test-strtr.js)', function () {
  it('should pass example 1', function (done) {
    var expected = 'hello all, I said hi'
    var $trans = {'hello' : 'hi', 'hi' : 'hello'}
    var result = strtr('hi all, I said hello', $trans)
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 2', function (done) {
    var expected = 'aaabaaccasdeooo'
    var result = strtr('äaabaåccasdeöoo', 'äåö','aao')
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 3', function (done) {
    var expected = 'aaaaaaaa'
    var result = strtr('ääääääää', 'ä', 'a')
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 4', function (done) {
    var expected = 'zyyx'
    var result = strtr('http', 'pthxyz','xyzpth')
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 5', function (done) {
    var expected = 'http'
    var result = strtr('zyyx', 'pthxyz','xyzpth')
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 6', function (done) {
    var expected = '2'
    var result = strtr('aa', {'a':1,'aa':2})
    expect(result).to.deep.equal(expected)
    done()
  })
})
