// warning: This file is auto generated by `npm run build:tests`, do not edit by hand
process.env.TZ = 'UTC'
var expect = require('chai').expect
var ini_set = require('/Users/kvz/code/phpjs/src/php/info/ini_set') // eslint-disable-line no-unused-vars
var ini_get = require('/Users/kvz/code/phpjs/src/php/info/ini_get') // eslint-disable-line no-unused-vars
var strcspn = require('/Users/kvz/code/phpjs/src/php/strings/strcspn.js')

describe('src/php/strings/strcspn.js', function () {
  it('should pass example 1', function (done) {
    strcspn('abcdefg123', '1234567890')
    var expected = 7
    var result = strcspn('abcdefg123', '1234567890')
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 2', function (done) {
    strcspn('123abc', '1234567890')
    var expected = 3
    var result = strcspn('123abc', '1234567890')
    expect(result).to.deep.equal(expected)
    done()
  })
})