// warning: This file is auto generated by `npm run build:tests`
// Do not edit by hand!
process.env.TZ = 'UTC'
var ini_set = require('../../../../src/php/info/ini_set') // eslint-disable-line no-unused-vars,camelcase
var ini_get = require('../../../../src/php/info/ini_get') // eslint-disable-line no-unused-vars,camelcase
var ord = require('../../../../src/php/strings/ord.js') // eslint-disable-line no-unused-vars,camelcase

describe('src/php/strings/ord.js (tested in test/languages/php/strings/test-ord.js)', function () {
  it('should pass example 1', function (done) {
    var expected = 75
    var result = ord('K')
    expect(result).toEqual(expected)
    done()
  })
  it('should pass example 2', function (done) {
    var expected = 65536
    var result = ord('\uD800\uDC00'); // surrogate pair to create a single Unicode character
    expect(result).toEqual(expected)
    done()
  })
})
