// warning: This file is auto generated by `npm run build:tests`
// Do not edit by hand!
process.env.TZ = 'UTC'
var ini_set = require('../../../../src/php/info/ini_set') // eslint-disable-line no-unused-vars,camelcase
var ini_get = require('../../../../src/php/info/ini_get') // eslint-disable-line no-unused-vars,camelcase
var strrev = require('../../../../src/php/strings/strrev.js') // eslint-disable-line no-unused-vars,camelcase

describe('src/php/strings/strrev.js (tested in test/languages/php/strings/test-strrev.js)', function () {
  it('should pass example 1', function (done) {
    var expected = 'dlevennoZ nav niveK'
    var result = strrev('Kevin van Zonneveld')
    expect(result).toEqual(expected)
    done()
  })
  it('should pass example 2', function (done) {
    var expected = 'Baha\u0301' // combining
    var result = strrev('a\u0301haB')
    expect(result).toEqual(expected)
    done()
  })
  it.skip('should pass example 3', function (done) {
    var expected = 'Z\uD87E\uDC04A' // surrogates
    var result = strrev('A\uD87E\uDC04Z')
    expect(result).toEqual(expected)
    done()
  })
})
