// warning: This file is auto generated by `npm run build:tests`
// Do not edit by hand!
process.env.TZ = 'UTC'
var ini_set = require('../../../../src/php/info/ini_set') // eslint-disable-line no-unused-vars,camelcase
var ini_get = require('../../../../src/php/info/ini_get') // eslint-disable-line no-unused-vars,camelcase
var strncmp = require('../../../../src/php/strings/strncmp.js') // eslint-disable-line no-unused-vars,camelcase

describe('src/php/strings/strncmp.js (tested in test/languages/php/strings/test-strncmp.js)', function () {
  it('should pass example 1', function (done) {
    var expected = 0
    var result = strncmp('aaa', 'aab', 2)
    expect(result).toEqual(expected)
    done()
  })
  it('should pass example 2', function (done) {
    var expected = -1
    var result = strncmp('aaa', 'aab', 3 )
    expect(result).toEqual(expected)
    done()
  })
})
