// warning: This file is auto generated by `npm run build:tests`, do not edit by hand
process.env.TZ = 'UTC'
var expect = require('chai').expect
var ini_set = require('/Users/kvz/code/phpjs/src/php/info/ini_set') // eslint-disable-line no-unused-vars
var ini_get = require('/Users/kvz/code/phpjs/src/php/info/ini_get') // eslint-disable-line no-unused-vars
var shuffle = require('/Users/kvz/code/phpjs/src/php/array/shuffle.js')

describe('src/php/array/shuffle.js', function () {
  it('should pass example 1', function (done) {
    var $data = {5:'a', 2:'3', 3:'c', 4:5, 'q':5}
    ini_set('locutus.strictForIn', true)
    shuffle($data)
    var $result = $data.q
    var expected = 5
var $data = {5:'a', 2:'3', 3:'c', 4:5, 'q':5}
ini_set('locutus.strictForIn', true)
shuffle($data)
    var result = $data.q
    expect(result).to.deep.equal(expected)
    done()
  })
})