// warning: This file is auto generated by `npm run build:tests`, do not edit by hand
process.env.TZ = 'UTC'
var expect = require('chai').expect
var ini_set = require('/Users/kvz/code/phpjs/src/php/info/ini_set') // eslint-disable-line no-unused-vars
var ini_get = require('/Users/kvz/code/phpjs/src/php/info/ini_get') // eslint-disable-line no-unused-vars
var prev = require('/Users/kvz/code/phpjs/src/php/array/prev.js')

describe('src/php/array/prev.js', function () {
  it('should pass example 1', function (done) {
    var $transport = ['foot', 'bike', 'car', 'plane']
    prev($transport)
    var expected = false
var $transport = ['foot', 'bike', 'car', 'plane']
    var result = prev($transport)
    expect(result).to.deep.equal(expected)
    done()
  })
})