// warning: This file is auto generated by `npm run build:tests`
// Do not edit by hand!
process.env.TZ = 'UTC'
var ini_set = require('../../../../src/php/info/ini_set') // eslint-disable-line no-unused-vars,camelcase
var ini_get = require('../../../../src/php/info/ini_get') // eslint-disable-line no-unused-vars,camelcase
var arsort = require('../../../../src/php/array/arsort.js') // eslint-disable-line no-unused-vars,camelcase

describe('src/php/array/arsort.js (tested in test/languages/php/array/test-arsort.js)', function () {
  it.skip('should pass example 1', function (done) {
    var expected = {a: 'orange', d: 'lemon', b: 'banana', c: 'apple'}
    var $data = {d: 'lemon', a: 'orange', b: 'banana', c: 'apple'}
    arsort($data)
    var result = $data
    expect(result).toEqual(expected)
    done()
  })
  it('should pass example 2', function (done) {
    var expected = {a: 'orange', d: 'lemon', b: 'banana', c: 'apple'}
    ini_set('locutus.sortByReference', true)
    var $data = {d: 'lemon', a: 'orange', b: 'banana', c: 'apple'}
    arsort($data)
    var result = $data
    expect(result).toEqual(expected)
    done()
  })
})
