// warning: This file is auto generated by `npm run build:tests`, do not edit by hand
process.env.TZ = 'UTC'
var expect = require('chai').expect
var ini_set = require('/Users/kvz/code/phpjs/src/php/info/ini_set') // eslint-disable-line no-unused-vars
var ini_get = require('/Users/kvz/code/phpjs/src/php/info/ini_get') // eslint-disable-line no-unused-vars
var natsort = require('/Users/kvz/code/phpjs/src/php/array/natsort.js')

describe('src/php/array/natsort.js', function () {
  it('should pass example 1', function (done) {
    var $array1 = {a:"img12.png", b:"img10.png", c:"img2.png", d:"img1.png"}
    natsort($array1)
    var $result = $array1
    var expected = {d: 'img1.png', c: 'img2.png', b: 'img10.png', a: 'img12.png'}
var $array1 = {a:"img12.png", b:"img10.png", c:"img2.png", d:"img1.png"}
natsort($array1)
    var result = $array1
    expect(result).to.deep.equal(expected)
    done()
  })
})