// warning: This file is auto generated by `npm run build:tests`, do not edit by hand
XMLHttpRequest = {}
window = {window: {},document: {lastModified: 1388954399,getElementsByTagName: function(){return [];}},location: {href: ""}}
process.env.TZ = 'UTC'
window.window = window
var expect = require('chai').expect
var ini_set = require('/Users/kvz/code/phpjs/src/php/info/ini_set')
var ini_get = require('/Users/kvz/code/phpjs/src/php/info/ini_get')
var each = require('/Users/kvz/code/phpjs/src/php/array/each.js')

describe('php.array.each.js', function () {
  it('should pass example 1', function (done) {
    each({a: "apple", b: "balloon"})
    var expected = {0: "a", 1: "apple", key: "a", value: "apple"}
    var result = each({a: "apple", b: "balloon"})
    expect(result).to.deep.equal(expected)
    done()
  })
})