// warning: This file is auto generated by `npm run build:tests`, do not edit by hand
process.env.TZ = 'UTC'
var expect = require('chai').expect
var ini_set = require('/Users/kvz/code/phpjs/src/php/info/ini_set') // eslint-disable-line no-unused-vars
var ini_get = require('/Users/kvz/code/phpjs/src/php/info/ini_get') // eslint-disable-line no-unused-vars
var key = require('/Users/kvz/code/phpjs/src/php/array/key.js')

describe('src/php/array/key.js', function () {
  it('should pass example 1', function (done) {
    var $array = {fruit1: 'apple', 'fruit2': 'orange'}
    key($array)
    var expected = 'fruit1'
var $array = {fruit1: 'apple', 'fruit2': 'orange'}
    var result = key($array)
    expect(result).to.deep.equal(expected)
    done()
  })
})