// warning: This file is auto generated by `npm run build:tests`
// Do not edit by hand!
process.env.TZ = 'UTC'
var ini_set = require('../../../../src/php/info/ini_set') // eslint-disable-line no-unused-vars,camelcase
var ini_get = require('../../../../src/php/info/ini_get') // eslint-disable-line no-unused-vars,camelcase
var current = require('../../../../src/php/array/current.js') // eslint-disable-line no-unused-vars,camelcase

describe('src/php/array/current.js (tested in test/languages/php/array/test-current.js)', function () {
  it('should pass example 1', function (done) {
    var expected = 'foot'
    var $transport = ['foot', 'bike', 'car', 'plane']
    var result = current($transport)
    expect(result).toEqual(expected)
    done()
  })
})
