// warning: This file is auto generated by `npm run build:tests`, do not edit by hand
process.env.TZ = 'UTC'
var expect = require('chai').expect
var ini_set = require('/Users/kvz/code/phpjs/src/php/info/ini_set') // eslint-disable-line no-unused-vars
var ini_get = require('/Users/kvz/code/phpjs/src/php/info/ini_get') // eslint-disable-line no-unused-vars
var krsort = require('/Users/kvz/code/phpjs/src/php/array/krsort.js')

describe('src/php/array/krsort.js', function () {
  it('should pass example 1', function (done) {
    var $data = {d: 'lemon', a: 'orange', b: 'banana', c: 'apple'}
    krsort($data)
    var $result = $data
    var expected = {d: 'lemon', c: 'apple', b: 'banana', a: 'orange'}
var $data = {d: 'lemon', a: 'orange', b: 'banana', c: 'apple'}
krsort($data)
    var result = $data
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 2', function (done) {
    ini_set('locutus.strictForIn', true)
    var $data = {2: 'van', 3: 'Zonneveld', 1: 'Kevin'}
    krsort($data)
    var $result = $data
    var expected = {3: 'Kevin', 2: 'van', 1: 'Zonneveld'}
ini_set('locutus.strictForIn', true)
var $data = {2: 'van', 3: 'Zonneveld', 1: 'Kevin'}
krsort($data)
    var result = $data
    expect(result).to.deep.equal(expected)
    done()
  })
})