// warning: This file is auto generated by `npm run build:tests`, do not edit by hand
process.env.TZ = 'UTC'
var expect = require('chai').expect
var ini_set = require('../../../../src/php/info/ini_set') // eslint-disable-line no-unused-vars,camelcase
var ini_get = require('../../../../src/php/info/ini_get') // eslint-disable-line no-unused-vars,camelcase
var range = require('../../../../src/php/array/range.js') // eslint-disable-line no-unused-vars,camelcase

describe('src/php/array/range.js (tested in test/languages/php/array/test-range.js)', function () {
  it('should pass example 1', function (done) {
    var expected = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    var result = range ( 0, 12 )
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 2', function (done) {
    var expected = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
    var result = range( 0, 100, 10 )
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 3', function (done) {
    var expected = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i']
    var result = range( 'a', 'i' )
    expect(result).to.deep.equal(expected)
    done()
  })
  it('should pass example 4', function (done) {
    var expected = ['c', 'b', 'a']
    var result = range( 'c', 'a' )
    expect(result).to.deep.equal(expected)
    done()
  })
})
